image: maven:3.3.9-jdk-8

# Default stages, this list can be removed
stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - /root/.m2/repository/

compile:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS compile'

test:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS test'

# To get this working you need to define a volume while configuring your gitlab-ci-multi-runner.
# Mount your `settings.xml` as `/root/.m2/settings.xml` which holds your secrets.
deploy:
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS deploy'
  only:
    - master
  # Archive up the built documentation site.
  artifacts:
    paths:
    - target/staging
